### ISSUE TITLE
Opening from hidden folders throw "Permission Denied" error

### ISSUE THREAD

**Issue by Yowlen** [glimpse-editor/Glimpse#375] opened 2020-04-09 18:46 UTC
Attempting to open a hidden folder via the file chooser or directly opening an image contained in a hidden folder via an external file manager results in a "Permission Denied" error.
![Screenshot_2020-04-09_14-46-22](https://user-images.githubusercontent.com/17078692/78929733-e7acaa80-7a70-11ea-8818-192a56d7980e.png)

I'm running the snap package, so I don't know if this is able to be replicated on the official distribution methods or if it's specific to the snap version.

**Comment by TrechNex** [comment] 2020-04-09 19:07
Thanks for raising this bug. Some quick diagnostic questions:

- Does your user have read permissions to the directory? (You can check with `ls -la`)
- Is your home directory on the same hard drive as your root partition?
- Have you checked the “Permissions” button in Ubuntu Software Center? (It will be in the same place as the “Install” button)

We can also check the Flathub installer in due course, and if it still happens verify if this was the behavior upstream originally intended.

**Comment by TrechNex** [comment] 2020-04-09 19:08
Also cc hellsworth in case this is expected behavior from Snapcraft

**Comment by Yowlen** [comment] 2020-04-09 19:47
- Already made sure the user had read and write permissions to the directory before posting. Apologies for not making that clear.
- /home directory is on a separate partition than root
- Not sure permissions apply, as the images load fine the moment I move them out of the hidden folder (in this case, `.ut2004`) and into a folder that isn't hidden

- Forgot to add up above, but symlinks cannot get around it, indicating Glimpse is attempting to decode symlinks to get the raw path. If I link that `~/.ut2004/ScreenShots` folder to, say, a subfolder in ~/Pictures, it'll still fail in navigating to that symlink in the same manner, despite being able to navigate and open everything else in the `~/Pictures` folder and even across other symlinks that don't point to hidden folders.

**Comment by Member1221** [comment] 2020-04-09 20:30
Seems to be a snap related issue, then?

**Comment by TrechNex** [comment] 2020-04-09 20:35
Confirmed I can recreate the problem with the snap by creating a `.hidden-test` directory and trying to read/write to it from inside Glimpse Image Editor.

During the UK public holiday tomorrow I'll verify if it also applies to Flathub & natively-built. If it doesn't, then it's snapcraft-specific. If it does, then we need to check if this is already reported as an upstream bug.

**Comment by Yowlen** [comment] 2020-04-09 22:11
Just tested the flatpak version and it works fine there, so this is apparently only an issue with the snap version.

**Comment by hellsworth** [comment] 2020-04-10 16:49
Right so the snap gives the user access to files/folders in $HOME *except* hidden folders. [This is by design](https://forum.snapcraft.io/t/syncthing-cannot-access-hidden-files-and-directories/745/3). Sorry for the inconvenience here.

**Closed** 2020-04-27 20:59 UTC
Labels: Bug, Linux, Packaging, Snap, Won't Fix

**Comment by d1moncom** [comment] 2020-05-07 07:27
There was a similar problem with directory access (symbolic link). Located on the removable media.

Help me:

`snap interfaces glimpse-editor`
`snap connect glimpse-editor:removable-media`

More info: https://d1mon.com/n/1698

**Comment by Yowlen** [comment] 2020-05-07 13:27
@d1moncom That's a separate issue and a workaround actually exists for that one. See this comment in issue #321 here: https://github.com/glimpse-editor/Glimpse/issues/321#issuecomment-597701982
