### ISSUE TITLE
Add Translators tab

### ISSUE THREAD

**Issue by libreajans** [glimpse-editor/Glimpse#228] opened 2019-11-22 16:51 UTC
It is shame of the Glimpse team that they have decided to get rid of the translator section on the About page.

If you decided to get rid of the translators, please delete all translations too.

Also, why are you deleting all of "Written by, Documented By, Artwork by" information too?

You have to keep these information and add your names too. 

Free/Open Source software does not mean you can delete my hard works and rebrand it with your name!

Please respect!

![aa](https://user-images.githubusercontent.com/6218679/69444420-59ee4e00-0d61-11ea-86f2-6643ef561ad5.png)
![bb](https://user-images.githubusercontent.com/6218679/69444422-5a86e480-0d61-11ea-910a-736b68daee64.png)

**Comment by Member1221** [comment] 2019-11-22 16:54
The upstream author information is available in [ORIGINAL_AUTHORS](https://github.com/glimpse-editor/Glimpse/blob/dev-g210/ORIGINAL_AUTHORS)
We plan to add a button that opens that file soon.

We also plan to redo some of the translations, that hasn't been set up yet; though. :)

**Comment by Member1221** [comment] 2019-11-22 16:58
This is related to this issue https://github.com/glimpse-editor/Glimpse/issues/179

**Comment by TrechNex** [comment] 2019-11-22 16:58
I've marked this as a 0.1.x candidate, but may get pushed out to 0.2.0. We do also have an issue open for this: #179 

We plan to acknowledge upstream contributions in the UI in a future release. We have not done so for 0.1.0 because there is currently no way to separate upstream vs downstream in the UI, and there are individuals who dislike that we chose to fork the project and that we know may not want to be credited as "Glimpse contributors".

As @Member1221 pointed out we do still include those names with the license and source code.

**Comment by Member1221** [comment] 2019-11-22 17:00
Update; it appears that in the original AUTHORS file, translators were not credited. We should definitely add translators to the file.

**Comment by TrechNex** [comment] 2019-11-22 17:02
I'm relieved that we didn't accidentally miss something off in that case. Is there a "translators" category in the `authors.xsl`? If not, then this would be a feature request rather than a bug, and therefore a duplicate of #179

**Comment by TrechNex** [comment] 2019-11-22 17:02
Scratch that, it wouldn't be a duplicate as we would be implementing a new "Translators" tab. In so doing we could probably add one for the Sponsor Contributors too.

**Comment by TrechNex** [comment] 2019-11-22 17:05
Confirmed the category doesn't currently exist in the XSL file, so it's possible this was implemented upstream in a later release. We'll see if this is included in 2.10.14, and if not we will work on implementing this.

**Comment by Member1221** [comment] 2019-11-22 17:06
Looked at current upstream source; it's not there. Translators are most likely fetched from somewhere else we might've missed.

**Comment by TrechNex** [comment] 2019-11-22 17:07
Indeed. We should make a note to raise this question with upstream as there could be some kind of `make` command that we are not aware of.

**Comment by Member1221** [comment] 2019-11-22 17:09
Seems like it's fetched from the .po files, so yeah seems like some broken build config that doesn't include the translators.

**Comment by TrechNex** [comment] 2019-11-22 17:09
So @libreajans thank you for bringing this to our attention. We did not deliberately omit the important work that translators do.

* We already fulfil our license obligations by providing the list of original authors with the source code.
* We have plans to credit the upstream contributors in the UI in a future release in a sensitive way that doesn't falsely credit them as Glimpse contributors.
* We will also raise a question with upstream to find out how they generate that tab and populate it.

**Comment by Member1221** [comment] 2019-11-22 17:11
Found out, seems like the tool gimp-mkenums parses the .po files and generates enums for each translation file. This is definitely something that isn't clean and something we should probably implement more cleanly; at least in our UI rewrite.

**Comment by TrechNex** [comment] 2019-11-22 17:12
Indeed. tbh there are probably all kinds of scripts scattered around the source code that we have not even started to explore yet. So we need issues like this to prompt us to fix these problems :)

**Comment by Member1221** [comment] 2019-11-22 17:25
I've traced down the issue @libreajans apparently the translation string for
translator-credits are not present in any of the translations, I think i will ASAP fetch those from upstream and paste them in to the translation files. :)

**Comment by TrechNex** [comment] 2019-11-22 17:27
Cool. So looks like this could be pushed out in a bugfix release.

**Comment by Member1221** [comment] 2019-11-22 17:29
Update: Apparently they are there but they aren't detected?
This is really odd...

**Comment by TrechNex** [comment] 2019-11-24 23:54
Leaving as a 0.1.x candidate for now, but noticed the screenshot provided from upstream was 2.10.15.

For reference Glimpse 0.1.0 uses 2.10.12 and Glimpse 0.2.0 will use 2.10.14. So If that is a new feature being brought in after those releases then we may lack functionality to do so.

If it is fixable on the current codebase, we should do that asap.

**Comment by TrechNex** [comment] 2019-11-30 08:16
Confirmed this is not fixable on the 2.10.12 base we currently use. This is pushed out to 0.2.0 which will be based on 2.10.14, which is a little closer to the version quoted in the screenshot.

**Comment by TrechNex** [comment] 2020-01-04 21:45
Confirmed with upstream that the 'Translators" tab was added in 2.10.14. It will be implemented when we move to Glimpse 0.2.0.

**Comment by TrechNex** [comment] 2020-01-04 21:47
Linking to #189 which is the tracking issue for the rebase of the next major release.

**Comment by TrechNex** [comment] 2020-02-09 13:06
Confirmed today that this tab is not present in upstream 2.10.14. This means it's a new change introduced on dev branch (hence 2.10.15 version number in screenshot), and will not be in a production release until 2.10.16.

This means it has to be pushed out until 0.3.0, as that will be the release that bases on 2.10.16.

**Comment by TrechNex** [comment] 2020-02-09 13:08
To confirm, we still intend to credit upstream contributors in the 0.2.0 release. See #179

**Comment by TrechNex** [comment] 2020-02-10 08:54
Someone has since corrected me that this tab appears in 2.10.14 after all. If that is the case it should be a 0.2.x candidate.

**Comment by TrechNex** [comment] 2020-02-21 15:38
The "Translated by" tab appears in our beta build of 0.1.2 if you select any language other than "System Language". See #300 for remaining changes.

**Comment by TrechNex** [comment] 2020-02-25 21:14
Proven to work in 0.1.2 beta, and last fixes applied today. Final release of 0.1.2 is due Monday 2nd March 2020 and will finally resolve this problem.

**Closed by TrechNex** 2020-02-25 21:14 UTC
Labels: Enhancement
