### ISSUE TITLE
Make GEGL and BABL submodules

### ISSUE THREAD

**Issue by chaomodus** [glimpse-editor/Glimpse#33] opened 2019-07-07 20:48 UTC
The code base is tightly coupled with particular versions of these upstream libraries, it seems as though they should be submodules in the codebase and built as part of the build system if the system doesn't provide the correct versions (or not if they are expilicitly excluded at build time for example for distribution packages).

**Comment by chaomodus** [comment] 2019-07-07 20:53
For reference the upstreams are:
https://gitlab.gnome.org/GNOME/gegl/
https://gitlab.gnome.org/GNOME/babl/

**Comment by TrechNex** [comment] 2019-08-04 03:14
This is a duplicate of #32 - please track the issue there.

**Closed by TrechNex** 2019-08-04 03:14 UTC
Labels: refactoring
