### ISSUE TITLE
Glimpse 0.1.2 crashes when I try to 'Open' a file

### ISSUE THREAD

**Issue by Krongii** [glimpse-editor/Glimpse#365] opened 2020-04-02 11:37 UTC
### Describe the bug
Glimpse 0.1.2 crashes when I try to 'Open' a file

### To Reproduce
1. Go to 'File'
2. Click on 'Open'
Windows advises: 'Glimpse Image Editor has stopped working'

Disabled Avast (anti-virus). Problem still there. 

Reinstall Glimpse - problem still there

GIMP 2.10.18 is intalled. Works fine.

### Expected behavior
I expected an image to open.

### Desktop (please complete the following information)
 - OS: Windows]
 - Version 7 - 32bit

**Comment by TrechNex** [comment] 2020-04-02 14:20
This is a known issue with the underlying versions of BABL and GEGL, which are dependencies of the main code.

We are trying to build newer ones for 0.1.4, but because upstream switched to a new build system (meson) we’re having to completely change the way we build & package the code for Windows.

We will know by early next week if the fix will be in 0.1.4 or will have to be postponed to a later release, but we’re working as fast as we can!

**Comment by TrechNex** [comment] 2020-05-01 18:21
Closing as duplicate of #265

**Closed by TrechNex** 2020-05-01 18:21 UTC
Labels: Duplicate
