### ISSUE TITLE
Split out libraries to submodules

### ISSUE THREAD

**Issue by Member1221** [glimpse-editor/Glimpse#32] opened 2019-07-07 20:45 UTC
Having everything in one repository makes quite the mess.

We should probably split everything out in to seperate repositories, then use meson to build each repository/submodule as neccesary.

**Comment by TrechNex** [comment] 2019-08-03 11:17
Meson has been dropped for 1.0.0 stream, but I think this is still worth doing.

**Comment by TrechNex** [comment] 2019-08-03 11:18
Duplicate of #33

**Comment by Member1221** [comment] 2019-08-04 03:06
@TrechNex i'd more say #33 is a duplicate of this issue, since i'm also refering to libgimp, etc.

**Comment by TrechNex** [comment] 2019-08-04 03:14
Apologies, I got muddled up between the two :sweat_smile:

**Comment by TrechNex** [comment] 2019-08-04 03:21
I also think it'd be sensible to add the glimpse-editor/glimpse-helper-scripts repo as a submodule as well to help people figure out the build process.

**Comment by TrechNex** [comment] 2019-08-20 19:48
This has been completed in dev-g210 branch

**Closed** 2019-08-20 19:48 UTC
Labels: refactoring
