### ISSUE TITLE
Strange behavior on export to /tmp : file never is written, though no error messages

### ISSUE THREAD

**Issue by davgross** [glimpse-editor/Glimpse#498] opened 2020-11-25 20:40 UTC
### Describe the bug
If I export to /tmp/foobar.png, Glimpse believes it has saved such a file but no such file is saved.

### To Reproduce
1. Create an image using Glimpse
2. Click on **File > Export As...**
3. Navigate to `/tmp` and choose a filename like `foobar.png`
4. Click **Export**
5. Click on **File > Export As...** again
6. notice that `foobar.png` is listed among the contents of the `/tmp` directory.
7. use your file manager or terminal to navigate to `/tmp`; try to find that file there; notice that no such file exists.

I do not notice this behavior for e.g. my home directory `~/` to which Glimpse exports files correctly

### Expected behavior
The file is exported as expected.

### Desktop (please complete the following information)
 - OS: Linux (Ubuntu)
 - Version 20.04

**Comment by TrechNex** [comment] 2020-11-26 09:48
Can you confirm if you installed Glimpse Image Editor through the Ubuntu Software Center, or via Flathub?

In both cases they are designed to act as sandboxed environments from the rest of your system, and as a result there are only certain directories you can read/write as standard.

Not being able to read/write directly to the `/tmp` directory is expected behaviour for Snaps and Flatpaks. The expectation is you'd save to home directory, then separately run your `mv` command.

If you do need that functionality, you could potentially try the AppImage, as that behaves more like a "universal binary" with direct access to the rest of the system. We're also working to make it easier for Linux distros to package our application as DEB and RPM from 0.3.0 onwards.

**Comment by davgross** [comment] 2020-11-26 15:10
Ah. I don't remember how I installed it. The typical way I install is `sudo apt install` then if that doesn't work I try to remember how `snap` works or go to the application website to see if there are install instructions there. I'm pretty sure I didn't use flathub... first I've heard of it.

I didn't realize that Snaps couldn't use the `/tmp` directory.

I'm curious though why Glimpse shows that the file write to `/tmp` succeeded (it shows the files in the app-internal directory listings) when the file isn't there. Shouldn't it show an error message if there's a directory permissions issue?

**Comment by TrechNex** [comment] 2020-11-26 19:00
It probably should imho @davgross.

Having done a bit of digging, I believe it's an upstream bug we inherited here: https://gitlab.gnome.org/GNOME/gimp/-/issues/3156

The GNU I.M.P developers have closed it as a "Won't fix" because they view it as a packaging problem that Canonical need to fix with Snaps. When I next get time, I will have a rummage through https://forum.snapcraft.io to see if there has been any progress on that.

I will double-check to see if our Flatpak has the same exception they mention in that ticket. If not, that might be something we might consider including. cc @BrainBlasted as they're more knowledgeable about Flatpak conventions.

**Closed** 2020-11-28 15:38 UTC
Labels: Linux, Question
